### ISSUE TITLE
fix(wordle): specific double letter case being added to not present array

### ISSUE THREAD

**Issue by kaylittle6** [csalinas-dev/csalinas-dev-site#37]
![image](https://github.com/csalinas-dev/csalinas-dev-site/assets/49996828/026e1dcd-c95c-46dc-a255-82b7efbc3fe4)

The 2nd ``E`` in ``TEETH`` is likely being added to the not present array, causing logic to fail on any successive guesses

Need to adjust logic to account for this type of scenario

**Comment by csalinas-dev** [comment]
Me too :(
![image](https://github.com/csalinas-dev/csalinas-dev-site/assets/10602830/b1bb150d-f017-49b7-afc3-70ad49a7ff8a)

**Comment by csalinas-dev** [comment]
While building the `absent`, `present`, and `correct` fields from the board, check if the absent letter is already in the `present` or `correct` fields. If so, add the index to that set. Otherwise, continue on adding it to the `absent` list.
